ronin-co/cli

src/commands/migration.ts

In addition to supporting app tokens, we now also support session tokens, which can be obtained by executing the `ronin login` command.

Allow session token for `--prod`

---

src/commands/migration.ts
src/utils/protocol.ts

To ensure the `getBatchProxy` function operates correctly, it was necessary for the global and local versions of ronin to be synchronized. To address the issue of version mismatch, we have updated the implementation to dynamically import `ronin` from the project's local `node_modules` directory, rather than relying on the globally installed version.

Use local `ronin` package

---

src/commands/migration.ts
src/utils/protocol.ts

Automatically create the migration directory when the `apply` command is executed and the directory is missing.

Automatically create migration directory

---

src/utils/field.ts
tests/fixtures/index.ts
tests/utils/apply.test.ts

A customer on Discord highlighted an issue where the CLI suggested renaming a field from `A` to `B` and `A` to `C` within the same migration creation process, which is illogical. This PR addresses the issue by ensuring that a field can only be renamed once per migration creation step.

Restrict field renaming to one occurrence

---

src/utils/misc.ts

This change ensures that, if an error is logged by the `ronin migration` command, the error is logged in a cleaner way.

Improved error logging

---

src/commands/migration.ts
src/utils/model.ts
tests/utils/model.test.ts

By default, in order to maximize efficiency, migrations should be created from the current state of the production database, not from the state of a local database, as that is the most common use case, even for larger apps.
When it comes to applying, however, migrations should ideally first be applied to a local database and tested there, which is something we will likely start defaulting to very soon, once it's possible to easily hook up a local DB to your app.

Use prod DB as basis for migrations

---

src/utils/field.ts
src/utils/migration.ts
tests/fixtures/utils.ts
tests/utils/apply.test.ts
tests/utils/queries.test.ts

This update ensures that we only consider `field.name` if it is explicitly defined. In SQLite, the name property does not exist; it is only present in the RONIN layer. Therefore, we only need to compare the defined name with the remote name if it is specified. If `field.name` is not defined, it will be automatically generated by the `compiler`. Furthermore, this fix revealed another bug in the tests. The compiler does not yet support a create query with triggers. Therefore, we added a temporary second query to create the triggers separately.

Resolved unnecessary table recreation in migrations

---

src/utils/space.ts

This PR fixes a small bug uncovered where if you are a member of multiple teams in a space the CLI will show the same space handle multiple times when selecting a space for the `apply` or `diff` command.
The way this has been fixed is by updating the query made to get the necessary member records to only include records where the `team` field is `null`.

Fix duplicate space handles when selecting a space

---

src/commands/apply.ts
src/utils/field.ts
src/utils/migration.ts

Previously, if the `ronin apply` command failed, the error was not displayed in the terminal, effectively swallowing the error message. This update ensures that errors are now properly passed to the console for visibility. Additionally, the default response for the rename prompt has been changed from "No" to "Yes".

Enhanced error message display

---

src/commands/apply.ts
src/commands/diff.ts
src/utils/config.ts
src/utils/model.ts
src/utils/space.ts

This change ensures that only the ID of the currently selected space is stored in `.ronin`, not its slug.
Additionally, the respective config property is now called `space` instead of `spaceId`, to avoid unnecessary complexity.

Only store space ID in config

---

src/utils/info.ts

This change prevents the following:
```bash
♥ ~ ronin -v
⠋ 6.0.23
```
Instead, it will now look as expected:
```bash
♥ ~ ronin -v
6.0.23
```
More changes will follow soon that will improve how spinners are handled in general, so that the `printVersion` function no longer needs to stop the spinner. Instead, it should never even be started in the first place, unless it is needed.

Do not print spinner for version

---

src/utils/field.ts
tests/fixtures/index.ts
tests/utils/apply.test.ts

A customer reported that the migration process created a protocol where a temporary table was generated with the columns already dropped, yet the migration still executed additional drop queries. This has been addressed in this update.
Additionally, I updated the renaming prompt from:
`Did you mean to rename field: name -> notName`
to
`Did you mean to rename field: user.name -> user.notName` for better clarity.

Skip drop queries for recreated tables in migration

---

src/utils/migration.ts
tests/utils/migration.test.ts

This change ensures that the query for creating models with no fields is as clean as possible.

Ensure clean query for creating models with no fields

---

src/commands/apply.ts
src/commands/diff.ts

This PR fixes a regression introduced in [PR #47](https://github.com/ronin-co/cli/pull/47) that affected the `diff --apply` command. Additionally, I noticed that some errors were being printed twice in the console, which has also been addressed.

Fix `diff --apply` with custom path

---

src/utils/field.ts
src/utils/format.ts
tests/fixtures/index.ts
tests/fixtures/utils.ts
tests/utils/apply.test.ts
tests/utils/format.test.ts

This update enables alteration to fields of type `link` with `kind: 'many'`. Additionally, I've reorganized the tests for improved clarity and eliminated much of the redundant code. I also introduced helper functions to format SQL statements, making them more readable.

Allow to alter link fields of kind `many`

---

bun.lock
src/commands/apply.ts
src/utils/space.ts

When executing `ronin apply`, users are prompted to select the desired migration to run, with migrations sorted by default. The latest migrations are displayed first. Additionally, the query syntax has been updated, replacing `including` with `using` in https://github.com/ronin-co/compiler/pull/127.

Correctly sort migrations in `apply` prompt

---

tests/fixtures/utils.ts
tests/utils/apply.test.ts

Currently, the CLI tests only handle migrations with empty tables, which is not adequate for ensuring a robust migration process. I have refactored the tests to follow a coherent structure, enhancing both clarity and maintainability. In this PR, I have added code to the tests to ensure that no rows are accidentally inserted.

Refactored tests and prepare for tests with records

---

src/utils/field.ts
src/utils/migration.ts
tests/fixtures/index.ts
tests/fixtures/utils.ts
tests/utils/apply.test.ts
tests/utils/field.test.ts
tests/utils/migration.test.ts

Previously, developers couldn't add required fields without default values in SQLite because adding a column to a table with existing rows would result in empty values, conflicting with the required property. Now, developers are prompted to set a temporary default value.

Migration now allows to add `required` fields

---

src/utils/field.ts
src/utils/migration.ts
src/utils/queries.ts
tests/utils/apply.test.ts
tests/utils/field.test.ts
tests/utils/migration.test.ts
tests/utils/queries.test.ts

In https://github.com/ronin-co/compiler/pull/144, we changed the behavior so that `name` and `pluralName` are no longer automatically regenerated when altering a model’s slug. Instead, we now set these values directly in the CLI. This PR resolves the resulting issue by ensuring that models receive the correct names after creating temporary tables.

Correctly name models after temporary model creation

---

src/utils/protocol.ts
tests/utils/protocol.test.ts

In most cases, not every query is needed during a migration, so we now import only the necessary queries.

Only import necessary queries

---

tests/index.test.ts

The error message format in Bun has been updated between versions, which is causing the tests to fail for some users.

Make tests work for all bun versions

---

src/utils/misc.ts
tests/integration.test.ts
tests/utils/misc.test.ts

This update enhances the CLI to automatically detect when a user defines a model with a forbidden slug. If a forbidden slug is detected, the CLI will inform the developer to make the necessary adjustments.

Detect models with forbidden model slugs

---

src/commands/init.ts
src/utils/model.ts
tests/index.test.ts
tests/integration.test.ts

When executing the `ronin init` command, if the target space already contains models, the types are automatically installed. Conversely, if there are no models present in the space, a directory is initialized for migrations, and a code definition file is created for the models.

Create ronin project structure on init

---

src/utils/protocol.ts
tests/utils/protocol.test.ts

The CLI was previously designed to automatically import only the necessary query types. However, it only verified if the queries started with the query type, which overlooked cases involving subqueries. For instance, a subquery like `add.model({slug: 'model1'}).with(() => get.model({slug: 'model2'}))` was not correctly handled. This PR addresses and resolves this issue.

Only import necessary query types in migrations

---

.gitignore
tests/index.test.ts

The tests did not run consistently across different machines because they depended on accessing global `npmrc` and `bufing.toml` files, which can differ between environments. 
Additionally, we mocked the `appendFile` function to prevent it from appending `.ronin` to `.gitignore` every time.

Mock global `.npmrc`and `bunfig.toml`

---

src/commands/apply.ts
src/utils/info.ts
src/utils/migration.ts
tests/index.test.ts

This change updates the `apply` command to also run the `types` command straight after in order to update the generated TypeScript types.
This can also be skipped by disabling the new `--types` global flag that is enabled by default.

Re-generate types after running `ronin apply`

---

src/utils/field.ts
src/utils/migration.ts
tests/utils/apply.test.ts
tests/utils/migration.test.ts

This pull request addresses an issue related to the renaming of temporary models. When creating temporary models, it is necessary to rename the model from `ronin_temp_yourModelSlug` to `yourModelSlug`. Additionally, the `name` and `pluralName` attributes need to be updated, as they are derived from the compiler. Previously, altering the model slug and names resulted in `undefined` values for `name` and `pluralName`. This PR fixes this bug by ensuring that the `name` and `pluralName` are correctly set during the renaming process.

Creating temp models caused undefined `name` and `pluralName`

---

bun.lock
package.json
src/commands/apply.ts
src/utils/database.ts
src/utils/model.ts
tests/fixtures/utils.ts
tests/utils/apply.test.ts

This change upgrades the `@ronin/engine` dependency to version `0.1.16` & subsequently includes some minor refactoring to support the latest api changes as part of the upgrade.

Upgrade RONIN engine

---

bun.lock
src/commands/diff.ts
src/utils/info.ts
src/utils/migration.ts
tests/index.test.ts

Create clean migrations with the `--clean` flag which diffs the model definitions against a clean (empty) database.

Create migration from scratch with `--clean`

---

bun.lock
package.json
src/utils/model.ts

This change makes it possible to use the slug "model" when defining models. For example, a modeling agency might want to do that in order to define the list of people they work with.
As a result, the `get.models()` query was changed to `list.models()`, in order to complete the separation of DDL (Data Definition Language) queries from DML (Data Manipulation Language) queries.
Additionally, a new `list.model('...')` query was added for retrieving a model with a specific slug. This is necessary in order for us to be able to diff two models using queries (before & after). The `list` query type will likely evolve further in the future, just like `create`, `alter`, and `drop` (of course "listing" a single model is not entirely logical).
Originally, the change was landed in …

Free up "model" slug for models

---

src/commands/diff.ts
src/utils/info.ts
src/utils/migration.ts
tests/index.test.ts

With the `--force-drop` flag we can now create migrations which drop all models. Also `--clean` has been renamed to `--force-create`.

Drop all models migration with `--force-drop`

---

bun.lock
src/commands/apply.ts
tests/index.test.ts

Enhance error handling for `ronin apply`: If no migration directory is detected, the command now throws an error and suggests using `ronin diff` first.

Error on `apply` without migration directory

---

src/commands/apply.ts
src/commands/init.ts
src/commands/types.ts
src/index.ts
src/utils/info.ts
src/utils/model.ts
tests/index.test.ts
tests/integration.test.ts

The `ronin init` command was experiencing issues with getting stuck during execution. In this update, we have resolved that problem. Additionally, we have cleaned up the codebase by removing a significant amount of unnecessary code, improving overall efficiency and maintainability.

Remove stale `@ronin-types` code

---

bun.lock
package.json
src/commands/diff.ts
src/utils/migration.ts
tests/fixtures/utils.ts
tests/utils/apply.test.ts
tests/utils/migration.test.ts

This pull request resolves an issue where modifying the `idPrefix` results in a temporary table being created with the fields from the models in code. This leads to the migration process generating `create` and `drop` queries for these fields, causing errors because the fields either already exist or have been removed.

Allow for updating `idPrefix` and fields

---

src/utils/misc.ts

The CLI encountered issues when used with projects created using `pnpm`. This problem arises because `pnpm` organizes packages in the `node_modules` directory differently compared to other package managers like `npm`, `bun`, or `yarn`.

Support for `pnpm`

---

src/commands/pull.ts
tests/index.test.ts
tests/utils/pull.test.ts

This pull request fixes the `ronin pull` command by checking for and creating the model definition directory if it doesn't exist, preventing crashes. Additionally, it ensures that the space ID is correctly passed and utilised during the pull process.

Fix missing model directory in `ronin pull`

---

bun.lock
package.json

As it turns out, bundlers must know the unique origin of a piece of code (e.g. a function) in order to de-duplicate it.
For example, if two packages both bundle the same package x, then the code of package x will be duplicated in both of those packages.
Now, even if something imports those packages and runs a bundler, the code of package x will still be present twice, since the bundler is unable to know that both packages are using the same package x at the same version.
We therefore have two choices: Put all of our organization's code into a single monorepo (where deduping happens because all dependencies are known locally, which is not an option for us) or use peer dependencies (this is what we will do).
Originally, the change was landed in https://github.com/ronin-co/syntax/pull/73.

Use peer dependencies

---

src/commands/apply.ts

Removed ineffective foreign key pragmas from migrations as they don't work within transactions.

Remove ineffective foreign key pragmas

---

bun.lock
package.json
src/commands/apply.ts
src/commands/diff.ts
src/commands/types.ts
src/utils/model.ts
tests/utils/apply.test.ts

The name "RoninError" is pretty meaningless, since it might stem from any component of the RONIN platform.
With the name "CompilerError", it becomes clear that the error stems from the compiler.
Originally, the change was landed in https://github.com/ronin-co/compiler/pull/181.

Provide helpful name for compiler errors
